import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {randomBytes,createHash,randomUUID} from 'node:crypto';
export const runtime='nodejs';
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const fail=(message:string,status=400)=>NextResponse.json({error:message},{status});
function clients(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,secret=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!anon||!secret)throw Error('Missing Supabase server configuration');return {auth:createClient(url,anon,{auth:{persistSession:false}}),admin:createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}})};}
async function verified(req:NextRequest){const {auth,admin}=clients();const access=req.headers.get('authorization')?.match(/^Bearer (.+)$/i)?.[1];if(!access)throw Error('Sign in required');const {data,error}=await auth.auth.getUser(access);if(error||!data.user)throw Error('Invalid login session');const {data:profile,error:profileError}=await admin.from('profiles').select('is_active').eq('id',data.user.id).single();if(profileError||profile?.is_active===false)throw Error('Account disabled');return {admin,user:data.user};}
export async function POST(req:NextRequest){try{const {admin,user}=await verified(req);const body=await req.json();if(!['fund-handover','expense-receipt'].includes(body.purpose))return fail('Invalid camera purpose');const transactionId=body.purpose==='expense-receipt'?String(body.transactionId||''):null;if(body.purpose==='expense-receipt'){const {data,error}=await admin.from('cash_transactions').select('actor_id,kind,proof_path').eq('id',transactionId).single();if(error||data?.actor_id!==user.id||data.kind!=='Expense'||data.proof_path)return fail('You cannot attach a receipt to this transaction',403);}
const token=randomBytes(32).toString('base64url');const expiresAt=new Date(Date.now()+10*60*1000).toISOString();const {data,error}=await admin.from('camera_sessions').insert({token_hash:hash(token),actor_id:user.id,purpose:body.purpose,transaction_id:transactionId,expires_at:expiresAt}).select('id').single();if(error)throw error;const origin=(process.env.NEXT_PUBLIC_SITE_URL||req.nextUrl.origin).replace(/\/$/,'');return NextResponse.json({id:data.id,url:`${origin}/capture/${token}`,expiresAt});}catch(e:any){return fail(e.message,401)}}
export async function GET(req:NextRequest){try{const {admin,user}=await verified(req);const id=req.nextUrl.searchParams.get('id');if(!id)return fail('Missing session');const {data,error}=await admin.from('camera_sessions').select('status,proof_path,expires_at').eq('id',id).eq('actor_id',user.id).single();if(error||!data)return fail('Session not found',404);return NextResponse.json({status:data.status,proofPath:data.proof_path,expired:Date.now()>Date.parse(data.expires_at)});}catch(e:any){return fail(e.message,401)}}
// Phone endpoint needs no login: a random single-use camera link is the sole credential.
export async function PUT(req:NextRequest){try{const {admin}=clients();const token=String(req.nextUrl.searchParams.get('token')||'');if(token.length<30)return fail('Invalid link',404);const tokenHash=hash(token);const {data:session,error}=await admin.from('camera_sessions').select('*').eq('token_hash',tokenHash).single();if(error||!session)return fail('Invalid link',404);if(session.status!=='waiting'||Date.now()>Date.parse(session.expires_at))return fail('Link used or expired',410);
const body=await req.json();const image=String(body.image||'');if(!/^data:image\/jpeg;base64,[a-zA-Z0-9+/=]+$/.test(image))return fail('Capture a JPEG photo using the phone camera');const raw=Buffer.from(image.split(',')[1],'base64');if(raw.length<100||raw.length>4*1024*1024)return fail('Photo must be 100 bytes–4 MB');
// Claim session before writing storage so concurrent submissions cannot reuse it.
const {data:claimed,error:claimError}=await admin.from('camera_sessions').update({status:'uploading'}).eq('id',session.id).eq('status','waiting').select('id').maybeSingle();if(claimError||!claimed)return fail('Link already used',410);
const path=`${session.actor_id}/phone-capture/${randomUUID()}.jpg`;const {error:uploadError}=await admin.storage.from('transaction-evidence').upload(path,raw,{contentType:'image/jpeg',upsert:false});if(uploadError){await admin.from('camera_sessions').update({status:'waiting'}).eq('id',session.id).eq('status','uploading');throw uploadError;}
const {error:saveError}=await admin.from('camera_sessions').update({status:'captured',proof_path:path,captured_at:new Date().toISOString()}).eq('id',session.id);if(saveError)throw saveError;
return NextResponse.json({ok:true});}catch(e:any){return fail(e.message)}}
