'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {peso,prettyDate} from '../lib/store';
type Account={id:string;email:string;display_name:string;role:string;is_active:boolean;created_at:string};
async function authHeaders(){const {data:{session}}=await supabase!.auth.getSession();if(!session)throw Error('Session expired');return {'Authorization':`Bearer ${session.access_token}`,'Content-Type':'application/json'};}
export function UserManagement(){const [users,setUsers]=useState<Account[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('Cashier');
 async function fetchUsers(){try{setLoading(true);const r=await fetch('/api/admin/users',{headers:await authHeaders(),cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setUsers(j.users||[]);setError('');}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void fetchUsers()},[]);
 async function create(){try{setLoading(true);const r=await fetch('/api/admin/users',{method:'POST',headers:await authHeaders(),body:JSON.stringify({name,email,role})}),j=await r.json();if(!r.ok)throw Error(j.error);setSuccess(j.message);setName('');setEmail('');await fetchUsers()}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function modify(u:Account,patch:object){if(!confirm('Apply changes to this account?'))return;try{setLoading(true);const r=await fetch('/api/admin/users',{method:'PATCH',headers:await authHeaders(),body:JSON.stringify({id:u.id,...patch})}),j=await r.json();if(!r.ok)throw Error(j.error);setSuccess('Account updated');await fetchUsers()}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <><div className="pagehead"><div><div className="eyebrow">Super Admin only</div><h1>User Management</h1><p className="muted">Invite employees, assign roles and manage access.</p></div><button className="btn ghost" onClick={()=>void fetchUsers()}>Refresh</button></div>{error&&<p className="notice" role="alert">{error}</p>}{success&&<p className="notice">{success}</p>}<div className="card" style={{marginBottom:18}}><h2>Invite New Account</h2><p className="muted small">The employee receives an email invitation to set their own password. Only Super Admin can invite users.</p><div className="grid2"><label>Full Name<input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Employee name"/></label><label>Email<input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="employee@example.com"/></label><label>Role<select className="input" value={role} onChange={e=>setRole(e.target.value)}><option>Cashier</option><option>Admin</option></select></label></div><button className="btn" disabled={loading||!name.trim()||!/^\S+@\S+\.\S+$/.test(email)} onClick={()=>void create()}>Send Invitation</button></div><div className="card"><h2>Accounts {loading?'(Loading…)':`(${users.length})`}</h2><div className="tablewrap"><table><thead><tr><th>Name / Email</th><th>Role</th><th>Status</th><th>Created</th><th>Controls</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.display_name}<br/><span className="muted small">{u.email}</span></td><td>{u.role}</td><td><span className={'badge '+(u.is_active?'approved':'explain')}>{u.is_active?'Active':'Inactive'}</span></td><td>{prettyDate(u.created_at)}</td><td>{u.role==='Super Admin'?<span className="muted">Protected</span>:<div className="hrow"><button disabled={loading} className="btn ghost" onClick={()=>void modify(u,{role:u.role==='Cashier'?'Admin':'Cashier'})}>Set {u.role==='Cashier'?'Admin':'Cashier'}</button><button disabled={loading} className="btn ghost" onClick={()=>void modify(u,{is_active:!u.is_active})}>{u.is_active?'Deactivate':'Activate'}</button></div>}</td></tr>)}</tbody></table></div></div></>}
type Rec={id:string;account:string;expected:number;actual:number;difference:number;note:string;created_at:string};
export function DiscrepancyModule(){const [account,setAccount]=useState<'Petty Cash'|'Funds'>('Petty Cash'),[actual,setActual]=useState(''),[note,setNote]=useState(''),[rows,setRows]=useState<Rec[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){if(!supabase)return;const {data,error}=await supabase.from('cash_reconciliations').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else {setRows((data||[]) as Rec[]);setError('')}}
 useEffect(()=>{void refresh()},[]);
 async function submit(){if(!supabase)return;try{setBusy(true);const n=Number(actual);if(!Number.isFinite(n)||n<0)throw Error('Enter a valid cash count');const {error}=await supabase.rpc('create_cash_reconciliation',{p_account:account,p_actual:n,p_note:note});if(error)throw error;setActual('');setNote('');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><div className="pagehead"><div><div className="eyebrow">Super Admin only</div><h1>Cash Discrepancy</h1><p className="muted">Compare counted cash with the operational Petty Cash or Funds ledger.</p></div></div><div className="notice" style={{marginBottom:18}}>Expected amount is calculated from all signed cash transactions, including Pending for Approval. This is not a full POS cash-drawer reconciliation.</div>{error&&<p className="notice" role="alert">{error}</p>}<div className="card" style={{marginBottom:18}}><h2>Record Cash Count</h2><div className="grid2"><label>Account<select className="input" value={account} onChange={e=>setAccount(e.target.value as 'Petty Cash'|'Funds')}><option>Petty Cash</option><option>Funds</option></select></label><label>Actual Cash Count (₱)<input className="input" type="number" min="0" step="0.01" value={actual} onChange={e=>setActual(e.target.value)}/></label></div><label>Reconciliation Note<textarea className="input" value={note} onChange={e=>setNote(e.target.value)} placeholder="Cash count details or observed issues"/></label><button className="btn" disabled={busy||actual.trim()===''} onClick={()=>void submit()}>Record Reconciliation</button></div><div className="card"><div className="hrow between"><h2>Reconciliation History</h2><button className="btn ghost" onClick={()=>void refresh()}>Refresh</button></div><div className="tablewrap"><table><thead><tr><th>Date</th><th>Account</th><th>Expected</th><th>Counted</th><th>Difference</th><th>Note</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{prettyDate(r.created_at)}</td><td>{r.account}</td><td>{peso(Number(r.expected))}</td><td>{peso(Number(r.actual))}</td><td><span className={'badge '+(Number(r.difference)===0?'approved':'explain')}>{Number(r.difference)===0?'Matched':Number(r.difference)<0?'Short':'Over'}: {peso(Number(r.difference))}</span></td><td>{r.note||'—'}</td></tr>)}</tbody></table>{rows.length===0&&<div className="empty">No reconciliations yet.</div>}</div></div></>}
export function AuditLogsModule(){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState('');async function load(){const {data,error}=await supabase!.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(200);if(error)setError(error.message);else{setRows(data||[]);setError('')}}useEffect(()=>{void load()},[]);return <><div className="pagehead"><div><h1>Audit Logs</h1><p className="muted">Real server-recorded database events (latest 200).</p></div><button className="btn ghost" onClick={()=>void load()}>Refresh</button></div>{error&&<p className="notice">{error}</p>}<div className="card tablewrap"><table><thead><tr><th>Time (PH)</th><th>Actor ID</th><th>Module</th><th>Record</th><th>Action</th><th>Details</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{prettyDate(x.created_at)}</td><td>{x.actor_id}</td><td>{x.entity_type}</td><td>{x.entity_id}</td><td>{x.action}</td><td>{JSON.stringify(x.detail)}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No recorded events yet.</div>}</div></>}
