'use client';
import {useEffect,useRef,useState} from 'react';
export default function CameraProof({onCapture,onBack}:{onCapture:(photo:string)=>void;onBack:()=>void}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null);
 const [error,setError]=useState(''),[picture,setPicture]=useState('');
 useEffect(()=>{let disposed=false;async function start(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});if(disposed){s.getTracks().forEach(t=>t.stop());return}stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play().catch(()=>{})}}catch{if(!disposed)setError('Camera unavailable or permission denied. Use HTTPS, allow camera access and retry.')}}start();return()=>{disposed=true;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}},[]);
 function capture(){const v=video.current;if(!v||!v.videoWidth){setError('Camera is not ready yet.');return}const canvas=document.createElement('canvas');const scale=Math.min(1,1000/v.videoWidth);canvas.width=Math.round(v.videoWidth*scale);canvas.height=Math.round(v.videoHeight*scale);canvas.getContext('2d')?.drawImage(v,0,0,canvas.width,canvas.height);setPicture(canvas.toDataURL('image/jpeg',0.65));}
 return <div><div style={{background:'#111',borderRadius:12,overflow:'hidden',margin:'15px 0'}}>{picture?<img src={picture} alt="Cash handover capture" style={{width:'100%',maxHeight:330,objectFit:'contain'}}/>:<video ref={video} muted playsInline autoPlay style={{width:'100%',maxHeight:330,objectFit:'contain'}}/>}</div>{error&&<p className="notice">{error}</p>}<div className="hrow between"><button className="btn ghost" onClick={onBack}>Back</button>{picture?<><button className="btn ghost" onClick={()=>setPicture('')}>Retake</button><button className="btn" onClick={()=>onCapture(picture)}>Submit Transaction</button></>:<button className="btn" onClick={capture}>Take Picture</button>}</div></div>;
}
