'use client';
import {useEffect,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {supabase} from '../lib/supabase';
type Session={id:string;url:string;expiresAt:string};
export default function PhoneCameraLink({purpose,transactionId,onCaptured,onBack}:{purpose:'fund-handover'|'expense-receipt';transactionId?:string;onCaptured:(path:string)=>void;onBack?:()=>void}){const [session,setSession]=useState<Session|null>(null),[state,setState]=useState(''),[busy,setBusy]=useState(false);
async function token(){const {data}=await supabase!.auth.getSession();if(!data.session?.access_token)throw Error('Please log in again');return data.session.access_token;}
async function generate(){setBusy(true);try{const r=await fetch('/api/camera-session',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({purpose,transactionId})});const j=await r.json();if(!r.ok)throw Error(j.error);setSession(j);setState('Waiting for phone photo…')}catch(e:any){setState(e.message)}finally{setBusy(false)}}
useEffect(()=>{if(!session)return;let alive=true;const interval=setInterval(async()=>{try{const r=await fetch(`/api/camera-session?id=${encodeURIComponent(session.id)}`,{headers:{Authorization:`Bearer ${await token()}`},cache:'no-store'});const j=await r.json();if(!alive)return;if(j.status==='captured'&&j.proofPath){clearInterval(interval);setState('Photo received');onCaptured(j.proofPath)}else if(j.expired){clearInterval(interval);setState('Link expired. Generate a new link.');}}catch{}},1800);return()=>{alive=false;clearInterval(interval)}},[session,onCaptured]);
return <div className="phone-link"><p className="muted">Generate a QR code on the laptop. Scan with the phone camera to open a one-time camera page. The image is saved privately to Supabase.</p>{session?<><div className="qr-wrap"><QRCodeSVG value={session.url} size={200} includeMargin/></div><p className="small muted">Expires: {new Date(session.expiresAt).toLocaleTimeString('en-PH',{timeZone:'Asia/Manila'})} PH time</p><div className="linkbox">{session.url}</div><button className="btn ghost" onClick={()=>void navigator.clipboard.writeText(session.url)}>Copy Link</button></>:<button className="btn" onClick={()=>void generate()} disabled={busy}>{busy?'Generating…':'Generate Phone Camera QR'}</button>}<p className="small">{state}</p><div className="hrow wrap">{session&&<button className="btn ghost" onClick={()=>{setSession(null);setState('')}}>New Link</button>}{onBack&&<button className="btn ghost" onClick={onBack}>Back</button>}</div></div>}
