import {supabase} from './supabase';
import {Data,LedgerEntry,PosEntry} from './store';
const db=()=>{if(!supabase)throw new Error('Missing Supabase environment variables');return supabase};
const check=(error:{message:string}|null)=>{if(error)throw new Error(error.message)};
const dataUrlToBlob=async(s:string)=>await(await fetch(s)).blob();
export async function uploadImage(image:string,kind:string){const c=db();const {data:{user},error:e}=await c.auth.getUser();check(e);if(!user)throw Error('Please sign in');const blob=await dataUrlToBlob(image);if(blob.size>5*1024*1024)throw Error('Maximum image size is 5MB');const extension=blob.type==='image/png'?'png':blob.type==='image/webp'?'webp':'jpg';const path=`${user.id}/${kind}/${crypto.randomUUID()}.${extension}`;const {error}=await c.storage.from('transaction-evidence').upload(path,blob,{contentType:blob.type||'image/jpeg',upsert:false});check(error);return path;}
export async function photoUrl(path?:string){if(!path)return undefined;const {data,error}=await db().storage.from('transaction-evidence').createSignedUrl(path,600);if(error)return undefined;return data?.signedUrl;}
export async function fetchAll():Promise<Data>{const c=db();const [{data:t,error:e1},{data:p,error:e2},{data:profiles,error:e3},{data:logs,error:e4}]=await Promise.all([c.from('cash_transactions').select('*').order('created_at',{ascending:false}),c.from('pos_accounts').select('*').order('created_at',{ascending:false}),c.from('profiles').select('id,display_name'),c.from('audit_logs').select('*').order('created_at',{ascending:false})]);[e1,e2,e3,e4].forEach(check);const names=new Map((profiles||[]).map((x:any)=>[x.id,x.display_name]));const events=new Map<string,{at:string;by:string;action:string}[]>();for(const x of (logs||[]).slice().reverse()){const k=`${x.entity_type}:${x.entity_id}`;events.set(k,[...(events.get(k)||[]),{at:x.created_at,by:names.get(x.actor_id)||'Staff',action:x.action+(x.detail?.note?`: ${x.detail.note}`:'')}]);}
 const transactions:LedgerEntry[]=await Promise.all((t||[]).map(async(x:any)=>({id:x.id,account:x.account,kind:x.kind,amount:Number(x.amount),category:x.category,description:x.description,actor:names.get(x.actor_id)||'Staff',createdAt:x.created_at,signature:(await photoUrl(x.signature_path))||'',proof:await photoUrl(x.proof_path),status:x.status,explanation:x.explanation,reviewerNote:x.reviewer_note,events:events.get(`cash:${x.id}`)||[]})));
 const pos:PosEntry[]=(p||[]).map((x:any)=>({id:x.id,client:x.client,phone:x.phone,vehicle:x.vehicle,plate:x.plate,concern:x.concern,items:x.items,payments:x.payments,costs:Number(x.costs),status:x.status,createdAt:x.created_at,closedAt:x.closed_at}));return {transactions,pos,manualSales:[]};}
export async function createCash(t:LedgerEntry){const sig=await uploadImage(t.signature,'signatures');const proof=t.proof?await uploadImage(t.proof,'proofs'):null;const {error}=await db().rpc('create_cash_transaction',{p_id:t.id,p_account:t.account,p_kind:t.kind,p_amount:t.amount,p_category:t.category,p_description:t.description,p_signature:sig,p_proof:proof});check(error);}
export async function attachProof(id:string,image:string){const path=await uploadImage(image,'proofs');const {error}=await db().rpc('attach_cash_proof',{p_id:id,p_path:path});check(error);}
export async function reviewCash(id:string,action:'approve'|'request'|'explain',note:string){const {error}=await db().rpc(action==='explain'?'explain_cash':'review_cash',action==='explain'?{p_id:id,p_note:note}:{p_id:id,p_action:action,p_note:note});check(error);}
export async function createPos(p:PosEntry){const {error}=await db().rpc('create_pos',{p_id:p.id,p_client:p.client,p_phone:p.phone,p_vehicle:p.vehicle,p_plate:p.plate,p_concern:p.concern,p_items:p.items,p_payments:p.payments,p_costs:p.costs});check(error);}
export async function closePos(id:string){const {error}=await db().rpc('close_pos',{p_id:id});check(error);}

export async function addPosPayment(id:string,amount:number,method:string){const {error}=await db().rpc('add_pos_payment',{p_id:id,p_amount:amount,p_method:method});check(error);}
