'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../../lib/supabase';
export default function SetPassword(){
 const [ready,setReady]=useState(false),[valid,setValid]=useState(false),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false);
 useEffect(()=>{let active=true;(async()=>{const {data:{session}}=await supabase?.auth.getSession()||{data:{session:null}};if(active){setValid(Boolean(session));setReady(true)}})();return()=>{active=false}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(password.length<12)return setError('Use at least 12 characters.');if(password!==confirm)return setError('Passwords do not match.');if(!supabase)return setError('Supabase is not configured.');setBusy(true);try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;setSuccess(true);setPassword('');setConfirm('');}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <main className="auth-shell"><div className="card auth-card"><h1>Set Your Password</h1><p className="muted">Cashier Management System · Secure account activation</p>{!ready?<p>Checking your session...</p>:!valid?<><div className="notice">Your invitation or reset session is missing or expired. Open the latest email link, or request a new one.</div><Link className="btn ghost" href="/auth/forgot-password">Reset password</Link></>:success?<><div className="notice">Password saved. Your account is ready.</div><Link className="btn" href="/">Continue to CMS</Link></>:<form onSubmit={submit}><label>New Password<input className="input" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={12}/></label><label>Confirm Password<input className="input" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={12}/></label>{error&&<div className="notice">{error}</div>}<button className="btn" disabled={busy} type="submit">{busy?'Saving...':'Save Password'}</button></form>}</div></main>;
}
